Add initial support for parallel to emit stage
antmicro/verilator-1 pull request #20
Opened 2022-09-08 10:21 UTC by kamilrakoczy

This PR adapts ThreadPool from: https://github.com/gezalore/verilator/commit/5eac78fca10241fbcc49f5f7ca5032a0997e5282 and adds parallelization to emit stage.

I'm also adapting CI scripts to run tests with and without parallelization enabled.

This changes reduced total time of emit in our large design from 144s to 80s.

2022-09-08 13:07 UTC, kbieganski requested changes
I'm not sure if _parallelism_ is the right name for this feature, as it might be confusing for the user (_parallelism_ vs `--threads`?). I suggest something simple like `--verilation-threads`.

2022-09-08 13:36 UTC, kamilrakoczy commented on src/V3EmitCImp.cpp
> +    std::list<AstCFile*>* m_filenames;  // filenames generated by this emit
I need to:
- insert new filenames at the end of the container
- read from the beginning of the container
I don't know exact number of elements that I want to insert.

I think list is better than vector as it doesn't need to re-allocate memory on new element when we exceed pre-allocated memory (but tbh, I haven't benchmarked this).

Do you know any other container that is better for this?

2022-09-08 14:07 UTC, kbieganski commented on src/V3EmitCImp.cpp
> +    std::list<AstCFile*>* m_filenames;  // filenames generated by this emit
When you read from the beginning, you also pop the item, right? If so, consider a deque. Otherwise a vector would be sufficient.

2022-09-09 08:58 UTC, kamilrakoczy commented on src/V3EmitCImp.cpp
> +    std::list<AstCFile*>* m_filenames;  // filenames generated by this emit
Ok, changed to deque.

2022-09-09 08:58 UTC, kamilrakoczy commented on src/V3Options.cpp
> +    DECL_OPTION("-parallelism", CbVal, [this, fl](const char* valp) {
Ok, changed to ``--verilation-threads``.

2022-09-09 09:00 UTC, kamilrakoczy commented on src/V3Options.cpp
> +        if (m_parallelism < 1) fl->v3fatal("--parallelism requires positive value: " << valp);
I know, but ``atoi`` is used in other places in ``V3Options`` to convert ``const char *`` to int, so I think it is ok.
``0`` will result in error message, so it should be fine.

2022-09-09 09:08 UTC, kamilrakoczy commented on src/V3Options.h
> +    int parallelism() const { return m_parallelism; }
Added,

2022-09-09 13:44 UTC, closed without merging